
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Nawaphum Noiwinit  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Ubon Ratchathani, Thailand


## Social Profiles
facebook: http://www.facebook.com/bhoom.ys  ## your facebook account url
twitter: https://twitter.com/Poom_Witcom  ## your twitter account url
linkedin: https://www.linkedin.com/in/nawaphum-noiwinit-806935148/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
